#!/bin/bash

docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker rmi $(docker images)
docker volume rm $(docker volume ls)
docker-compose down
sudo rm -rfv /home/ruslan/data/wp /home/ruslan/data/db
mkdir -p /home/ruslan/data/wp /home/ruslan/data/db
sudo killall -u mysql